### ISSUE TITLE
DeviceInfo.isHeadphonesConnected() always return false on Redmi 6 

### ISSUE THREAD

**Issue by whenmoon** [react-native-community/react-native-device-info#1009]
# Bug
I'm wondering if this is related to some kind of version incompatibility or just whether I can expect it to work - does it look like `isHeadphonesConnected()` should return `true` under these circumstances? Thanks very much!

## Environment info

`react-native info` output:

```bash
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 26.63 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
```

Library version: 5.5.4

## Steps To Reproduce

1. Plug in wired headphones to Redmi 6 running Android 8
2. run React Native application and log return value of `DeviceInfo.isHeadphonesConnected()`
...

Describe what you expected to happen:

1. `DeviceInfo.isHeadphonesConnected()` to return `true`
2.

## Reproducible sample code

```javascript
import DeviceInfo from 'react-native-device-info';

areHeadphonesConnected();

export const areHeadphonesConnected = () => {
  DeviceInfo.isHeadphonesConnected().then(enabled => {
    // true or false
    console.log('areHeadphonesConnected', enabled);
  })
}
```

**Comment by mikehardy** [comment]
well, you certainly have a minimal reproducible example! 

The sample app itself should reproduce this as well (it'll log that value) - have you tried with the example app? To be clear: I expect it to also have the problem - I do not actually think it will work where the code you posted above has a problem - just that if we know the example app shows it then I can test a few devices I have here as well, and you might be able to test others

**Comment by mikehardy** [comment]
Any more results?

**Comment by whenmoon** [comment]
Hi @mikehardy sorry for not replying sooner - I had problems getting the example app up and running - I'm going to try and test this asap, please leave the issue open and I'll come back to it as soon as I'm back on audio.

**Comment by CaptainJeff** [comment]
@mikehardy and @whenmoon 

I am having this same issue on my iPhone XR. iOS 13.4. React native 60.5

I've tried all sorts of stuff and its always returned false. Let me know if you want me to test any certain circumstances.

**Comment by mikehardy** [comment]
Strange - I don't use this method personally so I have no experience with it. I'd check stack overflow and compare any recommendations there with our code to see if there's something wrong. Do you have it working with any other hardware + software combos? In the end if there's a problem someone on this thread will need to generate a PR for the fix

**Comment by CaptainJeff** [comment]
Yeah i actaully have already played aroudn with a few of hte suggestions that I have found on stackoverflow and continue to get false with different objective-c API's 

But i'm going to keep playing around and I'll create a PR if I end up figuring it out

**Comment by CaptainJeff** [comment]
@mikehardy this actually seems to be related to being on a VOIP call at the same time.

This code works otherwise but when I'm on a call (I'm using https://github.com/blackuy/react-native-twilio-video-webrtc) it always returns false. I'm guessing there is something related to which audio track is being inspected

**Comment by mikehardy** [comment]
Fascinating! I know with Android you can enumerate devices and iterate to check status, I know that's totally different but is it possible to enumerate all tracks on iOS? I'm just thinking out loud and you've likely thought of everything in this area already since you're deep in it :-)

Am I correct in understanding that with the app not doing anything else and the phone just engaged in playing media or not, the current code works then? (just so I know where we are at)

Worst case if this isn't fixable we could at least update docs to reflect limitations

**Comment by CaptainJeff** [comment]
Ahh @mikehardy it was an easier fix that I would have thought

https://github.com/react-native-community/react-native-device-info/pull/1020

The portType changes when the VOIP call starts from a Bluetooth A2DP device to a Bluetooth Hands-Free Profile device and our check only accounted for A2DP. There are probably others we could/should include but there aren't clear examples of when those are returned so I left them out

**Comment by mikehardy** [comment]
@CaptainJeff solved at least one more class of headphone connectivity that was not handled on the iOS side but the original report here for Redmi 6 is still not handled. I will leave this open but it is tagged as needs information so it won't advance unless people help identify root cause and propose PRs - cheers

**Comment by mikehardy** [comment]
No response from submitter
