### ISSUE TITLE
iOS does not detect when user manually switches to low power mode

### ISSUE THREAD

**Issue by vvusts** [react-native-community/react-native-device-info#1026]
I am using **v5.6.1**
I want to detect if user triggered power save on device.
I thought that this would work but this triggers on power cable in.
Is there any other way to get `lowPowerMode` only when suer change this phone settings?
```
import { NativeEventEmitter, NativeModules } from 'react-native'
const deviceInfoEmitter = new NativeEventEmitter(NativeModules.RNDeviceInfo);
async componentDidMount() {
this.batteryListener = deviceInfoEmitter.addListener('RNDeviceInfo_powerStateDidChange', status => {
      // {batteryState: "charging", batteryLevel: 0.75, lowPowerMode: true}
});
```

**Comment by mikehardy** [comment]
No

It's a device API, the device triggers when the device triggers. You determine how you respond in your application code based on power state event contents

Most phones change lowPowerMode when they are plugged in

**Comment by vvusts** [comment]
Hi thanks for fast response.
I just don't understand how it's device trigger?
**On iPhone Settings > Battery > Low power mode (switch)**
User can change this. I thought that I can use device-info to detect that change somehow.

**Comment by mikehardy** [comment]
Oh! You are right, looks like we might be missing something here

https://github.com/react-native-community/react-native-device-info/blob/2dea0575e892466c3ddc0965fafb2252f2466497/ios/RNDeviceInfo/RNDeviceInfo.m#L78-L89

Specifically something like 

https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/LowPowerMode.html

```objective-c
    [[NSNotificationCenter defaultCenter] addObserver:self
       selector: @selector(yourMethodName:)
       name: NSProcessInfoPowerStateDidChangeNotification
       object: nil];
```

I am happy to merge a PR that does this, it should be a quick hack - go after it directly in node_modules to develop + test it by hooking that and emitting a new powerStateDidChange event, when you get it working use https://github.com/ds300/patch-package (fantastic! if you've never seen it) so that your fix never stops working for you, and submit the change as a PR, I can do a release quickly just no time for the *testing* (that's the part that really takes the time, IMHO)

**Comment by mikehardy** [comment]
I ended up needing this in my personal project so I took the time to patch it up, it's released in 5.6.2 please let me know how it goes

**Comment by tsdmrfth** [comment]
@mikehardy Hi. The problem still exists. I'm using version 8.1.7

**Comment by Immacio** [comment]
@mikehardy Problem still persists in v10.3.0. The hook returns unknown whenever low power mode is switched on or off. Will not accurately return the lowPowerMode status.
