### ISSUE TITLE
Output values not consistent with the library 

### ISSUE THREAD

**Issue by dbsali** [react-native-community/react-native-device-info#1033]
dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-device-info": "^5.6.1"   
  }

Values returned in console log:

![Capture](https://user-images.githubusercontent.com/65315154/84817817-30399480-afdb-11ea-890e-6bb7d962a39c.PNG)

Not sure why the values are being returned in JSON instead of single values. I am sending this values to server and it fails. Any suggestions ?

**Comment by mikehardy** [comment]
APIs return a Promise which you are referencing directly, you need to resolve the promise either with async/await or API_you_called().then(() -> { /* etc */ }

When I first started coding async javascript these results were always a puzzle, now I recognize them *immediately* as what a Promise looks like when you send it directly to console.log

Burn that visual pattern of little underscore-numbers into your mind so that you can recognize them immediately as well, it will save you time later :)

**Comment by dbsali** [comment]
Thank you !! it works.

What is the difference between getSerialNumberSync() vs getSerialNumber() ?

**Comment by mikehardy** [comment]
The difference is exactly as described in the documentation, and demonstrated in the example
