### ISSUE TITLE
Ideas for version 3

### ISSUE THREAD

**Issue by machour** [react-native-community/react-native-device-info#307]
At some point, we are going to have to release a BC breaking version in order to fix some inconsistencies in this library. While we're at it, we might want to rethink the implementation a bit.

Here are some of my findings after having spending some time triaging issues, reviewing pull requests and reading the source code:

### Return type inconsistency

Findings:
* getBuildNumber() returns a string on iOS, and a number on Android (#214). Should be a number IMHO
* The windows implementation sometimes returns "not available" when a feature is missing
* Some methods are not implemented at all on a target and causes exceptions when called. Example: getIPAddress()

Proposal:
* No method should throw an exception if not implemented.
* Exception should only be thrown for Android when a permission is missing
* Unimplemented methods should *always* return `undefined`.

### Namespacing

Findings:
The API is getting bigger and deals with a lot of mixed stuff (networking, telephony, calendar, ..).

Proposal:
I think that introducing some king of namespacing could help keeping it tidy:

```js
DeviceInfo.telephony.getPhoneNumber();
DeviceInfo.network.getMacAddress();
DeviceInfo.network.getIPAddress();
// ...
``` 

We would also split the native code files by namespace

### Naming

Naming is inconsistent: `getDeviceName()` vs `getBrand()`.

We should take advantage of namespaces introduction to tidy up names.

### Multi SIM

Currently, telephony related functions returns data for the first SIM card. Might be good to introduce multi SIM card support.

Same goes for network informations (#259)

---

Feel free to join the conversation and suggest other or better ideas!

**Comment by machour** [comment]
### Promises vs Callback

isPinOrFingerprintSet() returns a callback while getIPAddress and getMACAddress uses promises. 

Proposal: 
Stick to promises

**Comment by machour** [comment]
As mentioned in #314, we should be using either `Id` or `ID` consistently.

**Comment by machour** [comment]
Introduce listeners for configurations changes? https://github.com/rebeccahughes/react-native-device-info/pull/278#issuecomment-363507963

**Comment by mvanroon** [comment]
shouldn't methods that start with is (like isEmulator) return a boolean?

**Comment by machour** [comment]
@mvanroon thank you for jumping in, I was feeling kind of lonely here 😆 

All the `isXXXX` method normally already return a boolean, did you have a counter example?
(if a method is unsupported on a platform, it should return `undefined`)

**Comment by mvanroon** [comment]
poor guy!

I removed my initial comment because I though I misread the API.
I believe that isPinOrFingerprintSet() should either return a boolean or should be renamed if you're planning on having it return a promise. Wouldn't you agree?

**Comment by machour** [comment]
Agreed! thinking of introducing listeners for these cases as well (cf #278)

**Comment by mvanroon** [comment]
Not sure about listeners. They tend to only make sense when the state changes while running an app. I'd prefer promises.

```
getPinOrFingerprintState()
    .then(hasPinOrFingerPrint => {
       // do stuff
    })
```

**Comment by machour** [comment]
yes, something exactly like you're describing will definitely be in the API to get the current state.

But pin/fingerprint can be unset while your app is still running, and you may want to listen to that as well. I'm thinking of something generic like:
```
DeviceInfo.addListener('pinOrFingerprintState', function(state) { /* do you magic */})
```

🤔

**Comment by machour** [comment]
Ok so here's a first part of the namespacing/renaming I had in mind. I'm pretty sure it can be perfected:

```js
var DeviceInfo = {
  app: {
    getName: function() {}, // ex getApplicationName()
    getInstallTime: function() {}, // ex getFirstInstallTime()
    getUpdateTime: function() {}, // ex getLastUpdateTime()
    getInstanceId: function() {},
    getBundleId: function() {},
    getBuildNumber: function() {},
    getVersion: function() {},
    getReadableVersion: function() {},
  },
  os: {
    getApiLevel: function() {}, // android only?
    getName: function() {}, // ex getSystemName()
    getVersion: function() {}, // ex getSystemVersion()
  },
  sim: {
    getCarrier: function() {},
  },
  network: {
    getIpAddress: function() {}, // ex getIPAddress
    getMacAddress: function() {}, // ex getMACAddress
  },
  device: {
    getBrand: function() {},
    getId: function() {}, // ex getDeviceId
    getName: function() {}, // ex getDeviceName
    getManufacturer: function() {},
    getMaxMemory: function() {},
    getTotalMemory: function() {},
    getModel: function() {},
    getSerialNumber: function() {},
    getTimezone: function() {},
    getUniqueId: function() {},
    getUserAgent: function() {},
    is24Hour: function() {},
    isEmulator: function() {},
    isTablet: function() {},
    isPinOrFingerprintSet: function() {},
  },
  storage: {
    getFreeSpace: function() {},
    getTotalSpace: function() {},
  }
  screen: {
    getFontScale: function() {},
  },
  dunnoYet: {
    getDeviceCountry: function() {},
    getDeviceLocale: function() {},
  }
};

```

**Comment by mvanroon** [comment]
Re: event listeners

I suppose so. Do you know of any actual use cases for changing your app’s functionally or state depending on wether the user has activated a pin or not?

Re: namespacing
I would probably put country and locale under os. Why do you believe the namespacing is required?

**Comment by machour** [comment]
> Re: event listeners

I don't. The idea is to have listener for values that might changes during runtime (getManufacturer() wont, is24hour() could)

> namespacing

The API is getting bigger and deals with a lot of mixed stuff (networking, telephony, calendar, ..). IMO namespacing stuff would make the API clearer.

**Comment by cmcewen** [comment]
Hi @machour! Just got here via waiting on #417. When are you thinking for the 1.0 release?

Also, I saw your proposal about exceptions - I think unimplemented functions should throw an exception in JS. For example, `getPhoneNumber` should have some function logic that it checks that the current platform is Android and throws otherwise. I feel like it's up to the lib consumer to only call on the right platform. Otherwise they may get unexpected `undefined`s and never be aware.

**Comment by antoinerousseau** [comment]
Hoping to see #517 in v1.0 :)

**Comment by mikehardy** [comment]
https://semver.org/#how-do-i-know-when-to-release-100

This software is clearly being used in production :-). I propose the current version is basically moved as is to 1.0.0 and this entire discussion is renamed as "Ideas for version 2.0.0".

That way people will know for real if there are breaking changes, and until a 2.x release we don't have compressed semantic versioning like we do right now, where we can't add a feature without causing semver auto-updates (npm package.json dependency of `react-native-device-info": "^0.29.1"`) to fail to install updates on npm install even though they are backwards compatible...

**Comment by machour** [comment]
Sounds like a legit idea :)
I'll release 1.0.0 tonight unless someone say something in the meantime.

**Comment by mikehardy** [comment]
I like the idea of consistent Promises vs Callbacks and would definitely convert the one callback (isPinxxx) to a Promise. I could see the whole API be Promises, but at the very least, only Promises and no Callbacks

I like the idea of name-spacing, and I think of the things running Android as having feature areas like 

- "hardware" (things you can touch or see, like sdcards, the device itself, cameras, screen characteristics, number of SIM slots, bluetooth, battery, etc)
- "os" (or "system software", basic operating system, maybe even bootloader like TWRP if that is available but probably just "os" with version and vendor and security patch level, etc)
- "connectivity" (where all networking and carrier stuff could go since it seems to be pretty dynamic)
- "configuration" (things the user can set independent of anything else and could change - like is24hr, locale(s), accessibility features etc etc
- "app" - everything about the current app and its capabilities

This isn't a religious issue for me though, just trying to reason about the divisions in a way that will hopefully be the least-terrible way as new APIs are added to this module and new hardware no one thought of is added to devices

That's all I can think of at the API surface level. 

Under the covers I could see many things moving out of constants such that they are fetched fresh from the system every API call as they are dynamic (like IP address, timezone).

**Comment by machour** [comment]
react-native-device-info 1.0.0 published 🎉

**Comment by mikehardy** [comment]
I'll start a branch to see if I can turn these ideas into code in a little bit so we can land some of the other breaking changes proposed like #602 

If anyone has a favorite example of another module they use where the API namespace is separated into namespaces, let me know - I'd love to see recommended examples

**Comment by mikehardy** [comment]
thinking further, there is another react-native-community project that handles localization better and this isn't really device specific, we should remove these completely in device-info 2.0 in favor of this module: https://github.com/react-native-community/react-native-localize

**Comment by mikehardy** [comment]
Okay, so as more meta-2.0 work I chatted with the react-native-netinfo maintainer(s) since they were extracted from core and are in react-native-community now, and they agreed to be a home for APIs that were related to current connection information, and would accept a PR to move things there.

context here: https://github.com/react-native-community/react-native-device-info/issues/635

My goal is to have this package be a perfect, lean beast of a package that tells you everything you possibly can about the device's hardware (with the understanding that hardware is dynamic, so with listeners etc), but to purposefully eliminate any duplication of effort in react-native-community.

So far that means localization stuff to react-native-localize, network stuff to react-native-netinfo, and I pinged the carrier maintainer but received no response so that and IMEI will probably get full-fledged work here.

If anyone else sees APIs in here that seem like they should have a perfect home let's try to organize with that maintainer and share effort.

Cheers

**Comment by mikehardy** [comment]
I just scanned through our APIs for what it's worth, and the only other ones I could see re-homing would be package-related ones. I know there are some packages that handle packaging but I haven't seen them be very active and they are outside of react-native-community so I don't like the idea of peeling those out.

Which is to say, I think the localize and netinfo stuff are probably the moves for 2.0 here, and that's it. Looking through the PRs and Issues completely now, I don't have any other conceptual blockers before 2.0 work starts.

**Comment by mikehardy** [comment]
As we work on this and think about #614 / CI - there are also some easy to adopt react-native-community standards around lint / formatting / typings that have a nice example transition commit from the modal project: https://github.com/react-native-community/react-native-modal/pull/293

**Comment by mikehardy** [comment]
react-native-vitals apparently handles memory and storage really well, might defer to there for our disk space APIs which if I understand are busted at the moment #338  #346

**Comment by mikehardy** [comment]
implementation will begin in earnest shortly

* [ ] basic source formatting to community standards
* [ ] e2e / detox testing in CI with the current code
* [ ] namespacing / typing / reorg etc (probably move fully to typescript)
* [ ] conversion to promise returns everywhere
* [ ] mopup various dependent issues that alter implementation

That's the general idea anyway

**Comment by mikehardy** [comment]
Work is landing here https://github.com/react-native-community/react-native-device-info/tree/v3

**Comment by mikehardy** [comment]
v3 branch has the javascript API moved and windows and android ported so far, just iOS left to do

I'm not doing any namespacing or typescript right now, just moving it to Promise-based API and merging in all the pent up breaking changes

Hope to have it done tomorrow afternoon

**Comment by mikehardy** [comment]
This is released.

If anyone wants to try v3.0.0-beta.1 of react-native-device-info is up tagged on npm as @latest - it's a big ol' breaking change because instead of making your app startup really slow (like .6 seconds slower than it would otherwise) by loading everything in constants in init, it's all Promises now. It also evicts the deprecated WebView stuff that causes App Store warnings. I would especially love a Windows tester, I don't even have a test environment there so I just hacked it and prayed https://github.com/react-native-community/react-native-device-info/releases/tag/v3.0.0-beta.1

**Comment by mikehardy** [comment]
I'll use this comment to track the discrepancies / blockers between react-native-device-info v2 and v3 for status and info:

- [ ] [PR to react-native-localize](https://github.com/react-native-community/react-native-localize/pull/65) not accepted yet so transition is rough

Differences detected so far
- [ ] iOS isTablet returning 0 instead of boolean right now
- [ ] iOS supportedAbis returning raw string instead of string inside array now
- [ ] android deviceId different (emulator was 'goldfish_x86' now is 'android'?)
- [ ] android deviceName (emulator was 'unknown' on emulator w/no permission now is 'Android SDK built for x86' probably #735 - check other results)

TODO:
- [x] check iOS simulator and fix any API differences
- [ ] check iOS real device (phone #, notch, tablet, camera, bluetooth name, release build)
- [x] check android emulator
- [ ] check android real device (phone #, notch, tablet, camera, bluetooth, release build)

**Comment by mikehardy** [comment]
3.0.0-beta.3 is out, it should have the last breaking changes.

I still have a couple iOS v2->v3 discrepancies to clear up then this will likely be final

**Comment by mikehardy** [comment]
3.0.0-rc.1 is out, I'm going to integrate it to my work project now and check release builds, but I think it's good to go. Would love a windows tester otherwise I'm not sure if I broke anything or not there, but I don't have a rig to test

**Comment by mikehardy** [comment]
3.0.0-rc.4 is out and I can't think of anything else to do on it. So I'm going to close this but I'll wait for the react-native-localize PR to merge before releasing
