### ISSUE TITLE
Automatic date & time / Automatic time zone flags value

### ISSUE THREAD

**Issue by VaishaliHawaldar** [react-native-community/react-native-device-info#423]
Hi,

For some requirement we need the automatic date & time / automatic time zone flag values from Date & time Settings. Can you please provide this information like the way you have provided for is24Hours

This scenario can occur when user has selected a custom date & time / timezone on phone but we want the exact today date & time as per current timezone

![capture](https://user-images.githubusercontent.com/36033944/40911516-96f299b0-680c-11e8-85d9-dd7e3a5e1cc1.PNG)

**Comment by moh3n9595** [comment]
Same issue

**Comment by hasanal1995** [comment]
+1

**Comment by mikehardy** [comment]
Do not just +1 issues in github. It spams everyone with a comment but you have not actually offered anything of value (like a PR). Use the thumbsup on the original issue.

**Comment by mikehardy** [comment]
Running a poll with a proposal to defer to @react-native-community/react-native-localize package where this is likely handled better https://github.com/react-native-community/react-native-device-info/issues/627

**Comment by erkrujjawal786** [comment]
hi
i cannot get my country name where the device is locate.i am getting timezone but unable to find country name ,when i use getDeviceCountry() ,i am getting GB but currently i am in india.
can someone help me?

**Comment by mikehardy** [comment]
@erkrujjawal786 that is unrelated, it is bad form to post your own issue on an existing issue unless you are certain the details match, and in this case the issue is about automatic time things, not locale mismatches. Please open a new issue with as much details as you can (versions of everything, ideally the output of the included react-native-device-info example app as related to locale - either screenshots or maybe editing App.js to dump to a log in addition to dumping to the screen, and sending that in).

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-localize/pull/65

**Comment by daltonpimmelPi** [comment]
hi, someone managed to solve the problem, I have the same problem, I can get the information, but when I am inside the app and that information is not updated, just closing the app and opening again to update the information.

**Comment by mikehardy** [comment]
Those apis moved to the localization module and it's event based so should work

**Comment by daltonpimmelPi** [comment]
Thank you so much for answering @mikehardy .
 Do you have any example of use, because I can not find. Because the other events work.
RNLocalize.uses24HourClock: This one works when I change the device. But RNLocalize.usesAutoDateAndTime () doesn't, only if I close the app and open it again it updates the true or false information.

**Comment by mikehardy** [comment]
You'll have to chase this in that repository @daltonpimmelPi - I highly recommend basing all investigation off the example app there, so if there is a problem it is easily reproduced by the maintainer

**Comment by JohnRhaenys** [comment]
@daltonpimmelPi did you figure out a way to update the RNLocalize.usesAutoDateAndTime( ) in real time without restarting the app?

**Comment by mikehardy** [comment]
Yeah I just checked. Android offers no broadcast intent to hook to that would give the app control when that happens, letting the app know that a switch from auto to manual happened. Only if the time is set or timezone is set will the app get an event emitted from localize. The code in that library is doing a great job, as good as it can do
