### ISSUE TITLE
Processor architecture version for Android

### ISSUE THREAD

**Issue by hemantasapkota** [react-native-community/react-native-device-info#578]
## Description

Using the react-native-device-info library, I would like to query for processor architecture version for Android. This can be achieved by invoking ```System.getProperty("os.arch");```. Output example: armv8l armv7l

## Use Case

This property would be useful for telemetry / analytics and for uniquely identifying the device.

**Comment by mikehardy** [comment]
sounds interesting. Can be implemented on iOS as well https://stackoverflow.com/questions/19859388/how-can-i-get-the-ios-device-cpu-architecture-in-runtime

PRs are welcome

**Comment by hemantasapkota** [comment]
I think I might be able to send a PR. What should be the name of this property ? I'm thinking ```osArchitectureVersion```. Any other recommendations ?

**Comment by mikehardy** [comment]
@hemantasapkota that would be awesome. Naming is always opinionated, so this is just opinion. But I'd avoid 'os' because it's a hardware property, not an os-level property. I like the simply idea of just going with supportedABIs to match the Android call https://developer.android.com/reference/android/os/Build.html#SUPPORTED_ABIS and support returning the 1+ array entries sorted by preference right from the device

On iOS it looks like (from the last comment here) we'd just get a single entry https://stackoverflow.com/questions/19859388/how-can-i-get-the-ios-device-cpu-architecture-in-runtime

At the same time, I saw Xamarin didn't return the actual CPU type, they instead tried to make it more useful to the API consumer by instead giving you two flags 32-bit or 64-bit, then arm or x86. Maybe that's interesting as a second couple APIs, but just keeping it easy and going with the array from Build on Android or the single entry from iOS would be cool to me

**Comment by hemantasapkota** [comment]
@mikehardy I'll follow the strategy that you've put down. To summarise:

1. For android, we expose a property called ```supportedABIs`` which returns an array of supported architectures. The first item in the array is the preferred one.

2. For ios, we expose a property called ```cpuType`` as discussed in [1]

3. For windows, perhaps something called ```OSArchitecture``` from [2]

[1] https://stackoverflow.com/questions/19859388/how-can-i-get-the-ios-device-cpu-architecture-in-runtime
[2] https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.osarchitecture?view=netframework-4.7.2

**Comment by mikehardy** [comment]
I think it would be best if they normalized between the three, so they all fed into a call named something like "supportedABIs", and for iOS it just populated one entry in the array, for Windows I have no idea :)

**Comment by hemantasapkota** [comment]
sounds good. i'm on it...

**Comment by hemantasapkota** [comment]
closing this. thanks for all the help @mikehardy . you're awesome.
