### ISSUE TITLE
Warning spam

### ISSUE THREAD

**Issue by svipas** [react-native-community/react-native-device-info#629]
## Summary

|             |     |
| ----------- | --- |
| Version     | latest   |
| Affected OS | iOS   |
| OS Version  | latest   |

## Current behavior

`Battery state `unknown` and monitoring disabled, this is normal for simulators and tvOS.`

It happens very often, on almost every action...

<img width="1221" alt="Screenshot 2019-04-05 at 19 47 42" src="https://user-images.githubusercontent.com/10441177/55643410-b523fe00-57db-11e9-9ec0-5a8ae8001763.png">

## Expected behavior

No warning at all or only 1 per app run.

**Comment by mikehardy** [comment]
Yeah it is a little aggressive. You can do like this for now and I'll think about how to handle this. I want the warning because I feel like support costs are one of the main things that slow down module development (answering issues vs authoring fresh features) but spam is no good

Note I haven't tested this particular suppression you may need to tune the string it is hunting for if you could post that it works, or post what actually works you will potentially help others

```typescript
// There are always warnings we want to hide, this may end up in a separate file:
import { YellowBox } from 'react-native';
YellowBox.ignoreWarnings(['Battery state']);
```

**Comment by svipas** [comment]
@mikehardy ignore warning helped, I suggest to add this to README or to reduce the noisiness of this error.

**Comment by mikehardy** [comment]
I'm glad that helped! I'm still thinking about how noisy I want it to be (maybe even one warning is too much, to your original point) but I/we can add a note about warnings in the docs pretty easily, yes.

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/commit/88b27d32b97840fda47151170b3e778b5f4fd637
