### ISSUE TITLE
Mi A2 Lite also have Notch

### ISSUE THREAD

**Issue by msajadi832** [react-native-community/react-native-device-info#633]
android device "Mi A2 Lite" also have Notch!
[https://www.mi.com/global/mi-a2-lite/specs/](https://www.mi.com/global/mi-a2-lite/specs/)

Brand: xiaomi
Model: Mi A2 Lite

It's other name is "Redmi 6 Pro" but result of  getModel() is "Mi A2 Lite"
[https://www.gsmarena.com/xiaomi_mi_a2_lite_(redmi_6_pro)-9247.php](https://www.gsmarena.com/xiaomi_mi_a2_lite_(redmi_6_pro)-9247.php)

**Comment by machour** [comment]
Hi @msajadi832,

In order to speed up the integration, we will need the device model as detected by this library.
What is the value displayed when using `deviceinfo.getModel()` with the Mi A2 Lite?

You are also welcome to open a PR to integrate the phone to the notch devices, see here how it's done: https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L202

**Comment by machour** [comment]
Closed by #634
