### ISSUE TITLE
getIPAddress only returns WiFi IP on AppleTV and not the wired ethernet IP

### ISSUE THREAD

**Issue by respectTheCode** [react-native-community/react-native-device-info#635]
## Description

The Apple TV has WiFi and a Wired Ethernet jack. The `getIPAddress` method ignores the Wired Ethernet connection and returns the WiFi IP address or 0.0.0.0.

It is not widely used but iOS does support USB network adapters and these would also be ignored by `getIPAddress`.

## Use Case

We have an Apple TV app and we would like to show the IP address and connection status of both the Wired and WiFi connections in the UI.

**Comment by mikehardy** [comment]
@salakar / @matt-oakes - I'm tagging you guys because with react-native-device-info under the community umbrella now, and react-native-netinfo likewise alongside us, I was hoping to have a cleaner line around what device-info does, and eliminate intra-community duplication.

To me netinfo seems like it is currently about "you are connected or not" with a little extra information (expensive, speed maybe). 

This issue shows the kind of network information device-info is geared towards - a thorough interrogation of the device to the limits of API + hardware + permission.

It doesn't seem like netinfo can handle this sort of enhancement request as is, but at the same time it seems to me like the natural home.

So the philosophical question: as netinfo maintainers how do you feel about a thorough network interrogation being possible through netinfo APIs? If so I can send PRs and issues (and some of our implementation) over there. If not, we'll keep building network stuff over here most likely

**Comment by matt-oakes** [comment]
Part of me thinks that device info would be a good place for everything, however, it seems more geared towards "static" information about a device rather than situation specific information. So I agree that NetInfo seems like the right place for this information.

We have already had a feature request for getting the connected Wifi SSID (https://github.com/react-native-community/react-native-netinfo/issues/37) which would be part of the "enhanced information".

A PR with the implementation you currently have would be very welcome. It's on my TODO list to look at the API we currently have to make it easier to expand the type of information that the library returns and this PR might inform what we need for that 👍

**Comment by mikehardy** [comment]
Okay - a PR (really a push request, ha) to attempt moving "current connection related" information to netinfo goes on the todo list

device-info is about to get a revamp that makes it more listener/event oriented as hardware configuration itself is actually pretty dynamic, but it does still seem that network info should go in netinfo :-)

So then if I am understanding correctly the right thing for @respectTheCode to do is to open an enhancement request on react-native-community/react-native-netinfo, maybe linking to here?

@respectTheCode - For what it's worth there is zero support for real multi-interface anything here at the moment either so I don't think this creates an extra delay, it'll be the same starting-from-about-nothing time for anyone to address it either way

**Comment by respectTheCode** [comment]
I agree that netinfo is a more logical place for this. I looked for IP addresses in netinfo first.

I will open a new request.
