### ISSUE TITLE
when i use react-native link react-native-device-info  show error

### ISSUE THREAD

**Issue by Hideer** [react-native-community/react-native-device-info#641]
## Summary

|             |     |
| ----------- | --- |
| Version     | 1.5  |
| Affected OS | android   |
| OS Version  | all  |
| react | 16.8.3  |
| react-native | 0.58.6  |

## Current behavior

```
error:
Package name not found in XXX\android\app\src\debug\AndroidManifest.xml

But i have the file
```
## Expected behavior
normal link but not

**Comment by mikehardy** [comment]
Please include all the information on the issue template

**Comment by Hideer** [comment]
@mikehardy  I've made a few changes. Have a look

**Comment by mikehardy** [comment]
Hmm, might be that we have a problem linking on windows (you did not put the OS you develop on, but I am guessing based on direction of slashes in the path in th error). But no one else has reported so that makes me think this is something peculiar to your environment

Can you clone the repo and run the example? In general for any module I want to integrate I do that if they have an example, to make sure it runs and to see what sort of output to expect. You should try that to make sure.

Other than that, you might follow the manual linking steps to see what is missing - I am guessing it is in android/settings.gradle, but without seeing the contents of android/*.gradle and your full AndroidManifest.xml I'm unsure.

Examining the contents of those same files in the example vs the files in your project may get you to the answer

**Comment by Hideer** [comment]
Ok, I'll try it first

**Comment by Hideer** [comment]
oh！ deeply sorry， when i change `implementation "com.facebook.react:react-native:+"` , it  is  run ok ， i think it's not your problem， so sorry！
