### ISSUE TITLE
add support for check latest version of the application

### ISSUE THREAD

**Issue by martin-badin** [react-native-community/react-native-device-info#665]
Hello, would be great if this package should have support for check latest version of the application from the google play store and from the app store.

**Comment by Taym95** [comment]
But this has nothing to do with device info, right?

**Comment by martin-badin** [comment]
No with device info :)

**Comment by mikehardy** [comment]
Yeah, I think what you want is a separate module I work on. I will not put this functionality in device-info because ideally the virtual stores (Play Store, App Store, or 3rd party markets) handle this for you. Unless you have an app (like I do) that is not on the stores, then it's important but you also need so much more (like, the actual updates).  https://github.com/mikehardy/react-native-update-apk / https://www.npmjs.com/package/rn-update-apk
