### ISSUE TITLE
Latest version (1.8.0) breaks versions of Android before P (9.0)

### ISSUE THREAD

**Issue by hjames9** [react-native-community/react-native-device-info#666]
Hello,

I'm receiving a build failure in the latest version as my application is using Android O and the latest location features added to version 1.8.0 are not compatible.

.../node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:368: error: cannot find symbol
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                                                      ^
  symbol:   variable P
  location: class VERSION_CODES
../node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:370: error: cannot find symbol
        locationEnabled = mLocationManager.isLocationEnabled();

Was it intentional to break compatibility with versions of Android prior to P (9.0), which still has a very small user base?

Thanks.

**Comment by mikehardy** [comment]
Hi there! Thanks for the heads-up. First, don't make assumptions about userbase, P has a third now and growing on apps I work on. That is to say, I understand your frustration, but you don't need to make secondary arguments like size of userbase, just saying there was a compatibility break is sufficient :-), we follow semver and this was a minor release so this was obviously unintentional.

That said I have not encountered this before. I think the issue is that you have not updated your build SDK. You don't need to update your target SDK but you should keep your build SDKs up to date or we have a hard time adding new features with API gates like this.

I suppose we could move to the numbering instead of the codes and just check for SDK_INT >= 28 and then it wouldn't matter.

For developer backwards compatibility that is possibly best.

Can you try just putting 28 in there and see if it works? Could you separately try moving your build sdk to 28 to see if that works? I'd like to verify all my assumptions about the nature of the problem are correct and would work as possible solutions

**Comment by hjames9** [comment]
Changing to an integer for the SDK_INT fixes the first error, but not the second error as the API doesn't exist in my build SDK for locationEnabled.

Changing my build SDK to 28 fixes both build errors.

**Comment by mikehardy** [comment]
Okay - I'm not sure of a way around this. I guess I was naively assuming that folks would update their toolchain, but I can see how that could be an uncomfortable requirement. At the same time, I'm not aware of a way to do this API selection without the symbols present. So I have to figure whether this is a semver break or not, I'm going to look around and see what other packages have done.

I'm really happy to hear you've got a successful build now though :+1:

**Comment by mikehardy** [comment]
I think I'm going to go with caution on this one, I will pull the 1.8.0 shortly and re-release as 2.0 with a highlight that this is the first time we include API28 Java APIs and we require a compileSdk of 28 now. No intention to trip people up like this...

**Comment by hjames9** [comment]
I think that makes sense.   Thanks!

**Comment by mikehardy** [comment]
Okay, 1.8.0 is pulled and 2.0.0 is out - thanks again for the report, and especially thank you for testing those two fix possibilities - that really helped me get this done quickly

**Comment by Ej-leone** [comment]
i fixed mine by updating  the   build version , updating to 2.0.0 dint fix it

**Comment by mikehardy** [comment]
@Ej-leone - that's expected, it is why 2.0 was a breaking change, it requires action on the part of library consumers, the action being to alter build SDK to API28 so the symbols are available.

**Comment by singhaishwarya** [comment]
Try using /react-native-device-info@1.7.0 as it works for buildToolsVersion<=28
for higher versions of react-native-device-info(>1.7.0) one needs to have buildToolsVersion>=29
