### ISSUE TITLE
getDeviceName without bluetooth permission

### ISSUE THREAD

**Issue by chris-feist** [react-native-community/react-native-device-info#735]
# Feature Request

`getDeviceName` should be updated to use an api that doesn't require permissions. There is a newer [API](https://developer.android.com/reference/android/provider/Settings.Global.html#DEVICE_NAME) that allows this. There is also an [undocumented](https://stackoverflow.com/a/45696806) way of getting it without the permission.

## Why it is needed

Adding the Bluetooth permission just to get the device name is unnecessary and confusing to users.

## Possible implementation

```
if (Build.VERSION.SDK_INT >= 25) {
    return Settings.Global.getString(getContentResolver(), Settings.Global.DEVICE_NAME);
} else {
    return Settings.Secure.getString(getContentResolver(), "bluetooth_name");
}
```

### Code sample

Same as existing but without the Bluetooth permission

**Comment by mikehardy** [comment]
I like the idea - happy to take a PR so long as it is backwards-compatible + documents that you can use the 'maxSdkVersion' attribute in the manifest when declaring the permission so that doesn't show up for folks that have access to the new API https://developer.android.com/training/permissions/requesting#declare-by-api-level

**Comment by mikehardy** [comment]
I just implemented this for v3

**Comment by chris-feist** [comment]
Thank you! Sorry I don't have many devices to test with, so didn't implement it myself.

**Comment by mikehardy** [comment]
no problem. works so far on the emulator :-), and the implementation seems sane - I'm an android dev + react-native so I'm comfortable giving it a shot (obviously). Hoping to release an rc1 of v3 in the next day or so and we can all see.

**Comment by mikehardy** [comment]
I went a slightly different way with this one after testing.

Previously we were relying entirely on bluetooth name but with permission.

This proposed implementation worked but gave a different result, and in the end did not give my phone's actual system name despite it being set (!)

So rather than check for API25 and give priority to a new piece of information ("device_name") which apparently does not give great results, I just went with the no-permission-required "bluetooth_name" by itself.

Seems to work for me now on emulator and real device, we'll see how the implementation fairs in the wild
