### ISSUE TITLE
iOS Deprecated API Usage Warning for UIWebView ITMS-90809

### ISSUE THREAD

**Issue by Johan-dutoit** [react-native-community/react-native-device-info#756]
See https://github.com/react-native-community/react-native-webview/issues/819

I have not yet submitted a new version of the app, but I searched my node_modules and found that this module referenced UIWebView too.

See: https://github.com/react-native-community/react-native-device-info/blob/8efe2efaba6b01a1d48a0238ff91ab8e9d39f4ab/ios/RNDeviceInfo/RNDeviceInfo.m#L118

**Comment by radko93** [comment]
I could submit a PR for that but then the Android part would also have to be asynchronous (as `WKWebView` `evaluateJavascript` is asynchronous). Is that fine @mikehardy?

**Comment by mikehardy** [comment]
Dang. This may be the time to finally do the big promise-based breaking change. I've got a bit of time this morning maybe I can crank it out. I don't want to just trickle in async changes when everything needs to go async really.

@Johan-dutoit / @radko93 I read through the linked discussion and did not see any statement on *when* it would become a hard requirement and fail an app store build vs just a warning. Could one of you guys dig and find when this becomes a hard fail? That will help prioritize

**Comment by mikehardy** [comment]
@radko93 I would definitely appreciate a PR that implemented the required API change - while I may not ingest it as is (because I want to do all the async changes at once) it would be really really helpful to me to have the ObjC portion of the PR from someone who knew what they were doing :-). If you converted it to a Promise at the same time I could probably just include the commit raw into the promise-ify commit stream anyway, to maintain attribution

**Comment by Johan-dutoit** [comment]
@mikehardy can we assume it's going to be with iOS 13?  i.e. anything that targets iOS 13, which would mean less than 2 months away. 

The [documentation](https://developer.apple.com/documentation/uikit/uiwebview) currently states the following, although we will have to check back once 13 is released.

![image](https://user-images.githubusercontent.com/1611055/63946949-f5776780-ca6d-11e9-88de-1d2093c2a5c2.png)

Other than that, I've been unable to find a concrete timeline.

**Comment by mikehardy** [comment]
No one seems to know concretely in the react-native-community Discord chats or the webview component or stackoverflow. I think that's a reasonable guess though, thank you. If anyone posted the recommended ObjC changes that would help me :pray: and we could get something up quickly to start working through project-specific testing etc

**Comment by mikehardy** [comment]
This is merged and will release with v3

**Comment by ATranDev** [comment]
> Điều này được hợp nhất và sẽ phát hành với v3

When will v3 be released? I am really in need @mikehardy

**Comment by mikehardy** [comment]
No, no you aren't really in need. You're strongly in want, nothing more. It's a warning, the app store will still accept submissions.

Asking for your free stuff faster is not polite in the open source world :-)

That said, I might have a release candidate up tomorrow morning.

But if I met my untimely demise and you really thought you were in need for some reason, you could use patch-package to integrate the merged patch, or fork. You'd be fine because the source is open and you're a programmer

**Comment by mikehardy** [comment]
This is released.

If anyone wants to try v3.0.0-beta.1 of react-native-device-info is up tagged on npm as @latest - it's a big ol' breaking change because instead of making your app startup really slow (like .6 seconds slower than it would otherwise) by loading everything in constants in init, it's all Promises now. It also evicts the deprecated WebView stuff that causes App Store warnings. I would especially love a Windows tester, I don't even have a test environment there so I just hacked it and prayed https://github.com/react-native-community/react-native-device-info/releases/tag/v3.0.0-beta.1

**Comment by mikehardy** [comment]
I am planning on letting it incubate at least a couple days - plenty of time for good feedback. Final release maybe early next week. But you can rely on the v3 git branch, or the `@next` npm tag now if you want

**Comment by aksonov** [comment]
@mikehardy Is it possible to remove UIWebView from 2.x release? 3.0 requires new API to use and it breaks old API usage..

**Comment by rnnyrk** [comment]
Waiting for the v3 release to be stable. Btw I don't think your "No, no you aren't really in need. You're strongly in want, nothing more. It's a warning, the app store will still accept submissions." is valid. The Apple mail explicitly mentioned "Apple will **stop accepting** submissions of apps that use UIWebView APIs."

**Comment by mikehardy** [comment]
@rnnyrk tell me the date and I'll listen, until then my statement stands.

3.0.0-rc.1 has had no issues logged so I believe it's stable though I may add a companion sync API to it.

**Comment by Johan-dutoit** [comment]
Been using (only like 5% of it anyway) 3.0.0-rc.1 for a while now and no issues yet.

**Comment by rnnyrk** [comment]
@mikehardy I didn't mean this as an offense in any way. Just state what the Apple mail mentioned, which made me a little scared for my release. Updated to the RC now. Seems to run without any issues.

**Comment by mikehardy** [comment]
No worries @rnnyrk I don't take offense but I must be firm in my stance as the project as huge and wishy-washy remarks result in comment discussions that take time I don't care to spend ;-). So I wanted to be very concrete, for others that might come.

So to restate (since this will be the last comment now): Apple will continue accepting app submissions for now. There is no known date when they will stop. It is suspected they may stop when iOS 13 is in full release but that is a guess.

And of course we are working to resolve it.

Thanks everyone for the RC1 testing. I had so much difficulty with a semi-synchronous code-base and the fully async RC1 that I'm adding a parallel sync API for RC2 which is unfortunately a big change so I'll really appreciate further testing once it's out. Please follow along on #307  and #760 

Thanks

**Comment by kaphoto** [comment]
email: We identified one or more issues with a recent delivery for your app, "****" 1.0.0 (1.0.0). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**After you’ve corrected the issues**, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Best regards,

The App Store Team

So, currently my app is blocked completely due to the uiwebview thingy. I'm assuming this is across the board now.

**Comment by mikehardy** [comment]
@kaphoto this is thoroughly resolved through the ecosystem, the relevant issue in the react-native-webview repository has some good strategies to discover why you are still referencing the symbol, if you are. But the symbols are no longer in use in this repo.

**Comment by halabe15** [comment]
Find [solution here!](https://github.com/react-native-community/react-native-webview/issues/819#issuecomment-660708548)

**Comment by NSR88** [comment]
> Find [solution here!](https://github.com/react-native-community/react-native-webview/issues/819#issuecomment-660708548)

that is resolved for **react-native-webview**, but what to do for resolving the same for **react-native-device-info**?

**Comment by halabe15** [comment]
> that is resolved for **react-native-webview**, but what to do for resolving the same for **react-native-device-info**?

In my project I use `"react-native-device-info": "^5.6.2"` and everything goes just well.
