### ISSUE TITLE
Battery state `unknown` and monitoring disabled for iOS Simulator

### ISSUE THREAD

**Issue by ethanneff** [react-native-community/react-native-device-info#808]
This warning happens on iOS simulator for the following endpoints:

```ts
DeviceInfo.getBatteryLevel()
DeviceInfo.isBatteryCharging()
DeviceInfo.getPowerState()
```

Can this warning be silenced if on iOS and using a Simulator?

<img width="526" alt="Screen Shot 2019-09-22 at 1 26 43 PM" src="https://user-images.githubusercontent.com/2933593/65393976-dbfbcf80-dd3c-11e9-94b9-dea77c4f6702.png">

**Comment by Johan-dutoit** [comment]
You could do the following to silence it locally:

```
import { YellowBox } from 'react-native';

YellowBox.ignoreWarnings(["Battery state `unknown` and monitoring disabled"])
```

This message was intentionally added, so that developers realise it won't work as expected on the simulator.  We're open to ideas, if you have a better way of dealing with this?

i.e. If this doesn't exist, then presumably we'll get bombarded with issues saying it doesn't work.

**Comment by mikehardy** [comment]
I'm open to other ways but do not want people to expect it to work when it doesn't, and this is our best tradeoff idea so far. In my opinion every react-native app is going to have warnings they want to silence, so I figure it just slots in there. I have this block, for instance, in my bootstrap, and it changes over time but is never empty:

```typescript
YellowBox.ignoreWarnings([
  'Warning: Async Storage has been extracted',
  'Battery state',
  'componentWillMount',
  'componentWillUpdate',
  'componentWillReceiveProps',
]);
```
