### ISSUE TITLE
Can a solution be added to the README Troubleshooting section for why this project might not build for Android after linking due to AndroidX errors?

### ISSUE THREAD

**Issue by taylorkline** [react-native-community/react-native-device-info#811]
# Feature Request

Hi @mikehardy, I noticed that #809, #752, and #778 all seem similar, and I have ran across them by searching for the same message (specifically, I am getting [this error](https://github.com/react-native-community/react-native-device-info/issues/752#issuecomment-522393156) posted by @xclidongbo).

Our current `develop` branch works until we add `react-native-device-info` 3.1.4, then we can no longer build on Android, which is probably why so many people have ended up coming here to open an issue.

`npm install --save-dev jetifier && npx jetify -r && npx react-native run-android` still results in the same failure (we are on RN 0.59.10, so I figure we want to reverse jetify).

I understand that you do not want to debug AndroidX issues, but since this issue seems to be caused by adding this project (not necessarily by the project itself, but at least by adding it), perhaps it would be useful to figure out a resource that does troubleshoot this issue and linking to it from the Troubleshooting portion of the README?

Perhaps @xclidongbo, @lordenas, or @joelany have found a workaround for this issue by now?

## Why it is needed

Having a resource in the Troubleshooting section will prevent users from opening more issues or be a convenient resource to link to if someone does open a related issue.

## Possible implementation

A link to a StackOverflow post or something that provides guidance on the issue.

**Comment by mikehardy** [comment]
How bout you head over to the real location :-), remember, I'm the [jetifier](https://github.com/mikehardy/jetifier) author too. That's the spot. You'd want to include your android/build.gradle, your android/app/build.gradle, your AndroidManifest.xml and probably package.json as well in order to conclusively find the problem. Also if you want to know which dependency is transitively bringing in which other dependency you want `./gradlew :app:dependencies`.

We can make a troubleshooting guide over on jetifier if there are no bullet points already in the troubleshooting section that help you

But that's the place for the issue to go. This module is just one example of lots of modules that will trigger the AndroidX pain so it's the symptom, not the problem, thus my desire to not troubleshoot it here
