### ISSUE TITLE
NativeModule.RNDeviceInfo is null RN 0.61.2

### ISSUE THREAD

**Issue by ajouve** [react-native-community/react-native-device-info#851]
# Bug

We just moved our app to RN 0.61.2, and we have the following issue on Android:

<img width="309" alt="Screen Shot 2019-10-17 at 10 29 33" src="https://user-images.githubusercontent.com/2337492/67013152-0ab15f80-f0c9-11e9-8317-5d66e05ab26b.png">

## Environment info

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 111.60 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 24, 25, 26, 27, 28
      Build Tools: 25.0.2, 27.0.3, 28.0.3
      System Images: android-24 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.61.2
```

Library version: 4.0.1

## Steps To Reproduce

Use RN 0.61.2 and only do an import

```
import DeviceInfo from 'react-native-device-info';
```

there is no way to link manually with this version of react native, can be the issue

**Comment by RuairiOliver** [comment]
Same problem for me

**Comment by mikehardy** [comment]
Any time you have a native module that's null, it's a project setup problem, and debugging those is a time-sink for maintainers - sorry

If you can reproduce this by cloning this repo and running the example (or just copying the refresh-example.sh script and using it) then it's an issue

But it's not an issue - I'm using this fine in RN0.61.2

**Comment by mikehardy** [comment]
Look at the volume of these issues - none of them problems with the module :-(

https://github.com/react-native-community/react-native-device-info/issues?q=is%3Aissue+sort%3Aupdated-desc+RNDeviceInfo+is+null+is%3Aclosed

**Comment by matanrokach** [comment]
@mikehardy I guess it happens mostly after react-native upgrade, and it looks like a lot of users are experiencing this issue. It would be nice to have any solution here...
I am using react-native 0.61.5 and unfortunately having this issue as well.. 😪

**Comment by mikehardy** [comment]
@matanrokach there is no real "solution" because there is no module-specific "problem". It's the underlying technology. In react-native if you want to use a native module, you must link it in. There are a few ways to do this - you have to pick one and implement it correctly. Or you have a problem.

As a maintainer, all I can do is show people examples of exactly how to do it correctly, whether they do so or not is out of my control.

RN59 https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example-rn59.sh#L33

RN60+ https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh#L29

What most people miss is setting up the linking correctly when they go from RN59 to RN60. Specifically https://github.com/facebook/react-native/blob/master/template/ios/Podfile#L2 https://github.com/facebook/react-native/blob/master/template/ios/Podfile#L15 and https://github.com/facebook/react-native/blob/master/template/android/app/build.gradle#L218

**Comment by ShooterArk** [comment]
i have tried everything but its not working for me :(

`# platform :ios, '9.0'

target 'ABC' do
  
  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTVibration',
    'RCTLinkingIOS'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

`

can you help me out here ? thank you

**Comment by mikehardy** [comment]
@ShooterArk looks like you're trying to do pods with rn59? Is that right? That's basically unsupportable at this point. You need RN60+ in order to do Xcode 11 well, and you need Xcode 11 to do iOS13 which is a requirement (or about to be), right? At the same time, this library used to work fine but I used react-native link back in the RN59 days, I did not add it as a pod.
