### ISSUE TITLE
yarn is required to install this library with npm

### ISSUE THREAD

**Issue by twelve17** [react-native-community/react-native-device-info#936]
# Bug

Installing this package using `npm` throws this error:

```
npm ERR! prepareGitDep sh: yarn: command not found
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! syscall spawn
npm ERR! prepareGitDep npm ERR! file sh
npm ERR! prepareGitDep npm ERR! errno ENOENT
npm ERR! prepareGitDep npm ERR! react-native-device-info@5.4.1 prepare: `yarn build`
npm ERR! prepareGitDep npm ERR! spawn ENOENT
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the react-native-device-info@5.4.1 prepare script.
```

It appears it expects `yarn` to be installed.  If this is expected, it would be helpful if the documentation states as such.  However, the docs state you can use either `npm` or `yarn`.

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 128.77 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.2, 28.0.3, 29.0.0
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.59.10

```

Library version: 5.4.1

## Steps To Reproduce

1. Ensure "yarn" is *not* installed
2. Run "npm i" on a project depending on this library.
...

Describe what you expected to happen:

1. Installation completes successfully

## Reproducible sample code

N/A

**Comment by dphaener** [comment]
:+1: On this. It's crazy to expect everyone to have yarn installed to use this library.

**Comment by mikehardy** [comment]
haha yeah - that's unexpected. Sorry, and thank you @dphaener !

**Comment by mikehardy** [comment]
I don't disagree with the weird stuff comment, and I've experienced yarn as being faster (it parallelizes network fetches better) but that's no real answer. npm *should* work - this module won't be part of the "weird stuff" list at least

**Comment by twelve17** [comment]
For the record, I was not making a judgement call on yarn vs npm 😀

**Comment by gie3d** [comment]
When I added this library as a dependency in my project and run `npm i`, I don't see any issue. However if I clone this project and run `npm i`, then I found the issue that relates to yarn. 

At the package.json and found that most commands in scripts are called by using yarn (such as prepare: yarn build). So think this might be the case and changing it to `npm` instead of `yarn` might be a more default option, in my opinion. Could I submit a pull request on this?

**Comment by mikehardy** [comment]
npm is packaged with node whereas yarn is optional, so at least for any path a normal user would take, yes, please PR away. I don't like mixing dependency managers but I also prefer yarn personally (as do the other maintainers here) so for non-essential (i.e., maintainer-only commands) I think it's a toss up. Probably should pick one and go with it (which would be npm I suppose. @Johan-dutoit what do you think? I'm inclined to just say "okay, it's npm now" and move on, feels like it could turn into something like a whitespace debate otherwise, but maybe I'm missing something?

**Comment by dphaener** [comment]
Would changing the `prepare` script to just run `bob build` solve this problem without enciting an npm vs yarn debate?

**Comment by mikehardy** [comment]
unknown, never tried it?

**Comment by mikehardy** [comment]
also for the record I'm more practical than that, I do not intend to debate really, I'm a lot more decisive then that, I'll just merge or do what is necessary to get it working and move on, assuming everyone is reasonably cool with it

**Comment by twelve17** [comment]
I'm reasonably cool 😎







I mean 🤓

**Comment by Johan-dutoit** [comment]
I don't see why we can't change it to npm.   I'm in agreement about using/preferring yarn, however I'm also of the opinion to not force it down someone's throat.

**Comment by mikehardy** [comment]
we're all good then - my open source queue is a bit backed up but I'll put this one out first. Thanks guys.

**Comment by mikehardy** [comment]
Please re-test with 5.4.2 just released, thanks again all
