### ISSUE TITLE
@React-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null

### ISSUE THREAD

**Issue by nidsnitesh** [react-native-community/react-native-device-info#942]
# Bug

 getting this error after importing 
import DeviceInfo from 'react-native-device-info';

## Environment info

  "react-native": "^0.60.4",
  "react-native-device-info": "^5.0.4",

i also have added ext block in my android/build.gradle
```buildscript {
    ext {        
        firebaseIidVersion = "19.0.1"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
    classpath 'com.android.tools.build:gradle:3.4.2'
    classpath 'com.google.gms:google-services:4.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}```


its working if i am doing manual liking but after that my js bundle is not reloading

**Comment by mikehardy** [comment]
If you can reproduce it with the example, then this is an issue, if you cannot (and you won't be able to, since this is a project integration issue) then it's a project integration issue. Something wasn't installed correctly and you'll have to go through your project (or look at the example) to see how to install it correctly

**Comment by nidsnitesh** [comment]
@mikehardy went through the example code base and i am doing the same the way you are doing

**Comment by mikehardy** [comment]
Insufficient: what I want to hear is "I ran the example and it worked (or did not work)". That's the reproduction. It will show it works, which will show the problem is project-specific and out of reach for us to help. There *will* be a difference between the example and your project's integration, and it will be your root cause
