### ISSUE TITLE
App version from Package.json

### ISSUE THREAD

**Issue by Deepp0925** [react-native-community/react-native-device-info#980]
# Question

How do I read the app version specified in package.json file?

getVersion always returns 1.0

**Comment by mikehardy** [comment]
getVersion is returning that native version of your app, which your build process should be incrementing (it's in AndroidManifest.xml or in the plist file for android or ios respectively). If you store your "real" version in package.json you'll need scripts to synchronize them during build into the native parts of android or ios. That's important because the app stores are based on those numbers and have no idea what a package.json is

Perhaps you want something like this: https://github.com/szhigunov/react-native-npm-version
