### ISSUE TITLE
Can we get build type with this package

### ISSUE THREAD

**Issue by pankajgupta1** [react-native-community/react-native-device-info#988]
# Feature Request

I want to get build type info in react native code. In android I have 3 build types: 

```
buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        releaseStaging {
            signingConfig signingConfigs.release
            matchingFallbacks = ['release']
        }
        release {

        }
    }

```
## Why it is needed

I am making seprate build for staging and production. I want to show the build type in my react native code.

_For an example I am using code push for sending updates. I want to send updates for them separately. For this reason I had to make the new releaseStaging build type._

**Comment by mikehardy** [comment]
The library can do almost anything if the underlying APIs support it. I'm not sure this has any API support but if you propose a PR I can take a look and merge it if it's good

**Comment by mikehardy** [comment]
(in my experience it's easier to have separate back-ends and use something that works for both platforms - like a different bundle id on iOS and a different application Suffix on android so that it really is a different app that you can have separate on your devices for parallel testing - firebase apps have the same challenge and there are heaps of articles online about how to do this)
